import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

export default function Home(): JSX.Element {
  return (
    <div className="container mx-auto pt-2 text-center">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Let's Go</h1>
      <Link href="/quiz">
        <h2 className="cursor-pointer bg-indigo-700 text-gray-200">Quiz</h2>
      </Link>
      <footer className="">
        <a href="" target="_blank" rel="noopener noreferrer">
          Powered by NotAwakeStudio
        </a>
      </footer>
    </div>
  )
}
